### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-0j3kh6cz-build/setup.py'

### ISSUE THREAD

**Issue by numairmansur** [automl/random_forest_run#32]
`pip install git+git+https://github.com/automl/random_forest_run` 

gives me:
```
Collecting git+https://github.com/automl/random_forest_run.git (from -r all_requirements.txt (line 12))
  Cloning https://github.com/automl/random_forest_run.git to /tmp/pip-0j3kh6cz-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-0j3kh6cz-build/setup.py'
```

**Comment by sfalkner** [comment]
Installing the python bindings of the random forests directly from the git repository is no longer possible. You have to install them via ``` pip install pyrfr ``` That will solve your problem.

**Comment by numairmansur** [comment]
Thanks
