### ISSUE TITLE
(New) Installation error

### ISSUE THREAD

**Issue by janvanrijn** [automl/random_forest_run#44]
On Ubuntu 16.04, swig and Cython are installed. Is there anything else that I need? 

```
Collecting pyrfr
  Using cached https://files.pythonhosted.org/packages/21/4c/58533c51ab301f61d3521dc4cd29ba8145eed8f11b84f70aba9fd28f6aca/pyrfr-0.4.0.tar.gz
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/janvanrijn/anaconda3/envs/openml-multitask/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8xQhnL/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp33qToPpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyrfr
  copying pyrfr/__init__.py -> build/lib.linux-x86_64-2.7/pyrfr
  running build_ext
  building '_regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/pyrfr
  gcc -pthread -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/janvanrijn/anaconda3/envs/openml-multitask/include/python2.7 -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,-rpath=/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_regression.so
  building '_util' extension
  swigging pyrfr/util.i to pyrfr/util_wrap.cpp
  swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
  gcc -pthread -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/janvanrijn/anaconda3/envs/openml-multitask/include/python2.7 -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,-rpath=/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_util.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-8xQhnL/pyrfr/setup.py", line 42, in <module>
      cmdclass={'install': CustomInstall}
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 238, in run
      self.run_command('install')
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-8xQhnL/pyrfr/setup.py", line 9, in run
      build.run(self)
  TypeError: unbound method run() must be called with build instance as first argument (got CustomInstall instance instead)
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /home/janvanrijn/anaconda3/envs/openml-multitask/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8xQhnL/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y2NuV5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/pyrfr
    gcc -pthread -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/janvanrijn/anaconda3/envs/openml-multitask/include/python2.7 -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-2.7
    g++ -pthread -shared -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,-rpath=/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_regression.so
    building '_util' extension
    swigging pyrfr/util.i to pyrfr/util_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
    gcc -pthread -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/janvanrijn/anaconda3/envs/openml-multitask/include/python2.7 -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/janvanrijn/anaconda3/envs/openml-multitask/compiler_compat -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,-rpath=/home/janvanrijn/anaconda3/envs/openml-multitask/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -L/home/janvanrijn/anaconda3/envs/openml-multitask/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/_util.so
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8xQhnL/pyrfr/setup.py", line 42, in <module>
        cmdclass={'install': CustomInstall}
      File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-8xQhnL/pyrfr/setup.py", line 9, in run
        build.run(self)
    TypeError: unbound method run() must be called with build instance as first argument (got CustomInstall instance instead)
    
    ----------------------------------------
Command "/home/janvanrijn/anaconda3/envs/openml-multitask/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8xQhnL/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-y2NuV5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8xQhnL/pyrfr/
```

**Comment by janvanrijn** [comment]
https://github.com/automl/auto-sklearn/issues/394

Same mistake, accidently created a Python 2 env.
